### PR TITLE
Update hyper to 0.10

### PR DESCRIPTION
**Pull request by equal-l2**
Add hyper-native-tls since hyper 0.10 has dropped out-of-box HTTPS support.

### CODE REVIEW

**Comment by equal-l2** [comment]
This PR is now obsolete since hyper 0.11 has released.
I'll make another PR for that.

**Comment by k0pernicus** [comment]
Hello @equal-l2,
Actually, I think the project is no longer updated.
You can contribute to [Zou](https://github.com/k0pernicus/zou) if you want - a fork of Snatch, with an additional feature: download from mirrors support (in testing).
I plan to update `hyper` for Zou, using `hyper-v0.11` and `hyper-tls` for SSL support.

**Comment by equal-l2** [comment]
~~Could you place a link to Zou in README.md then?~~
I've misunderstood you're a member of this project, sorry.

**Comment by k0pernicus** [comment]
No worries :-)
@Jean-Serge Can you do that please?

**Pull request closed without merging**
