### PR TITLE
Default threads number depends on the local core number

### PR DESCRIPTION
**Pull request by Jean-Serge**
Resolution proposition for #5

### CODE REVIEW

**Comment by k0pernicus** [comment]
I don't agree with this PR - actually, you get the number of CPUs (physical cores) of the machine, not the number of threads (global / per core) of this one.
Based on the [documentation of the `num_cpus` crate](http://ironframework.io/doc/num_cpus/index.html), the number of threads to use for _Snatch_ is `num_cpus::get() * num_cpus::get_physical()`.

**Comment by Jean-Serge** [comment]
Yes and no. Even if we were talking about core numbers instead of CPUs we should consider to launch a thread for each CPUs because that is the way our OS is seeing it.

**Comment by k0pernicus** [comment]
Sure, otherwise I think we should get the number of `physical` CPUs by default, instead of `logical` CPUs, as considering [this issue](https://github.com/seanmonstar/num_cpus/issues/5).

**Comment by Jean-Serge** [comment]
Thanks for the link I didn't understand this.

**Pull request merged**
